### ISSUE TITLE
dotfiles

### ISSUE THREAD

**Issue by BFGriffith** [BFGriffith/dotfiles#1]
> Hidden 🗂️ folders／directories 🗃️ or files 📂 used for storing user configurations／preferences or preserving states for various utilities or applications… 💾
# `.dotfiles` 📋
* In Unix‑like operating‑systems, any file or folder that starts with a dot character (for example, `/home/user/.config`), commonly called a “dot file” or `dotfile`, is typically treated by operating‑systems as hidden꞉ that is, the `ls` command does not display them unless the `-a` or `-A` flags (`ls -a` or `ls -A`) are used. In most command‑line shells, wildcards will not match files with names that start with `.` unless the wildcard itself starts with an explicit `.`
* `dotfiles` are typically NOT truly a security mechanism because access to them is not inherently or automatically restricted; typically, they’re “hidden” by most operating‑systems, but a primary intent for this is arguably to simply not overly “clutter” the display of the contents of directory listings with files the user may not have directly created or may not wish to casually visually display…
* press `Ctrl`＋`H` (Windows／Linux) or `⌘`＋`Shift`＋`.` (MacOS) to show hidden files 🔎
## History 🔙
> A convention arose of using “dotfiles” in the user’s home directory to store per‑user configurations or informational text. Early uses of this were the well‑known dotfiles꞉ `.profile`, `.login`, and `.cshrc`, which are configuration files for the `Bourne` shell＆`C` shell＋shells compatible with them, in addition to `.plan` or `.project`, both used by the `finger`＆`name` commands…
---
### 📋 TODO꞉ 🎯
- [ ] `.config`
- [ ] defaults to record＆restore System‑Preferences＋other MacOS configurations
- [ ] organize dotfiles setup into multiple script files
- [ ] checklist of steps to decommission computer before wiping drive or system reset
- [ ] create a bootable USB installer for MacOS
- [ ] integrate cloud services into dotfiles process (Dropbox, iCloud, Google Drive, OneDrive, etc.)
- [ ] `.ackrc` configuration for the `Ack`／`Ag` search tool, such as ignored directories＆filetypes…
- [ ] `.inputrc` custom key‑bindings＆macros for the `Readline` library used by shells like `Bash` or `ZSH`
### `bash` 🐚
- [ ] `.bashrc`
- [ ] `.bash_profile`
### `C` 🐚
- [ ] `.cshrc`
### `Emacs` 📝
- [ ] `.emacs`
### `git`
- [ ] `.gitconfig`
- [ ] `.npmrc` registry URLs, cache locations, etc. for `npm` (Node) package‑manager
- [ ] `.yarnrc` registry URLs, cache locations, etc. for `Yarn` package‑manager
### `Sublime` 📝
- [ ] `.sublime-settings`
### `tmux` ◫
- [ ] `.tmux.conf` configurations for the `Tmux` terminal multiplexer including key‑bindings, window‑splits, etc.
### `zsh` 🐚
- [ ] `.zshrc`
### `vim` 📝
- [ ] `.vimrc`
---
- [ ] Holman does dotfiles: This is a popular repository by Zach Holman that contains his personal collection of dotfiles. It includes configurations for various tools like Git, Vim, etc. 🗃️＝[holman/dotfiles](https://github.com/holman/dotfiles)
- [ ] Mathias Bynens dotfiles: Mathias Bynens has a comprehensive collection of dotfiles for MacOS. It covers configurations for shells, editors, and other command‑line tools. 🗃️＝[mathiasbynens/dotfiles](https://github.com/mathiasbynens/dotfiles)
- [ ] Paul Irish dotfiles: Paul Irish is a well‑known web‑developer, and his dotfiles repository includes configurations for a productive development environment. It covers tools like Git, Sublime‑Text, etc. 🗃️＝[paulirish/dotfiles](https://github.com/paulirish/dotfiles)
- [ ] Amix’s `Vimrc`: If you're specifically looking for Vim configurations, “Amix’s Vimrc” repository is worth checking out. It provides a highly customizable Vim configuration with extensive plugin support. 🗃️＝[amix/vimrc](https://github.com/amix/vimrc)
- [ ] `skwp` dotfiles: skwp's dotfiles repository focuses on providing a robust setup for MacOS users. It includes configurations for tools like Zsh, Vim, and Tmux. 🗃️＝[skwp/dotfiles](https://github.com/skwp/dotfiles)
* https://www.daytona.io/dotfiles/ultimate-guide-to-dotfiles
